uploads = []
generated = []

[[outputs]]
id = "beEngrLG9e7AukmU0lX7q"
uri = "file://vsr-technologies-hostinger.tar.gz"
type = "unspecified"
title = "VSR Technologies — Final Static Site (Hostinger Ready)"
